name: shared_widget
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  effective_dart: 1.3.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.0.0-beta.0
  flutter_inner_drawer:
    git:
      url: git@github.com:bikcrum/flutter_inner_drawer.git
      ref: bugfix/type-casting
  flutter_staggered_animations: ^1.0.0
  form_builder_extra_fields: ^7.0.0-alpha.6
  form_builder_validators: ^7.0.0
  get: ^4.3.8
  lottie: ^1.1.0
  page_flip_builder: ^0.1.3
  scroll_to_index: ^2.0.0
  shared_preferences: ^2.0.5
  toggle_switch: ^1.2.0
  url_launcher: ^6.0.18

dependency_overrides:
  flutter_form_builder:
    git:
      url: git@github.com:Bdaya-Dev/flutter_form_builder.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
