name: shared_widget
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  auto_size_text: ^3.0.0-nullsafety.0
  toggle_switch: ^1.2.0
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  
  effective_dart: 1.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

